name: Assign Reviewers

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get maintainers list
        run: |
          pr_author="${{ github.event.pull_request.user.login }}"

          maintainers=$(curl -s -H "Authorization: token ${{ secrets.buildcli }}" \
            "https://api.github.com/repos/${{ github.repository }}/collaborators" | \
            jq -r --arg author "$pr_author" '.[] | select(.permissions.push == true and .login != $author) | .login')

          echo "Found maintainers:"
          echo "$maintainers"

          # Safe multiline export
          {
            echo 'MAINTAINERS<<EOF'
            echo "$maintainers"
            echo 'EOF'
          } >> $GITHUB_ENV

      - name: Assign maintainers as reviewers
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.buildcli }}
          script: |
            const pr = context.payload.pull_request;

            if (!pr) {
              console.log("This script only runs on pull_request events.");
              return;
            }

            const prAuthor = pr.user.login;
            const reviewers = process.env.MAINTAINERS.split("\n").filter(Boolean);
            const filteredReviewers = reviewers.filter(r => r !== prAuthor);

            if (filteredReviewers.length === 0) {
              console.log("No eligible reviewers found (excluding PR author).");
              return;
            }

            try {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                reviewers: filteredReviewers
              });
              console.log(`✓ Assigned ${filteredReviewers.length} reviewers:`, filteredReviewers);
            } catch (error) {
              console.error("❌ Error assigning reviewers:", error.message);
            }
