name: Auto Label Issues and Pull Requests

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-label-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Auto Label PRs
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  auto-label-issues:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - name: Auto Label Issues
        uses: github/issue-labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
